#!/bin/bash
# List the last N items in specified directory in
# reverse time order (newest on bottom).
# 
# You can achieve the same thing with a bash funtion, perhaps
# in your ~/.bashrc e.g.:
#
# lslt () { command ls -lhatr --color=always "$1" | tail -"$2"; }
#
# Or even fancier . . . 
#
#lslt () { 
#if [ $# -lt 1 ] 
#then
#        #type lslt
#        echo "Usage: lslt /foo N (optional)"
#        echo "Will perform ls -lhatr | tail -N"
#else
#        command ls -lhatr --color=always "$1" | tail -"$2";
#fi
#}
#
# Note however, the 'alias' commnad alone will not correctly handle args.

if [ $# -lt 1 ]
then
	echo "Usage: $0 /foo N (optional)"
	echo "Will perform ls -lhatr | tail -N"
	exit 1  
fi

dir=$1
echo "Listing $dir . . . "
ls -lhatr --color=always $dir | tail -$2
